### ISSUE TITLE
new github action - push new tag to pypi

### ISSUE THREAD

**Issue by styk-tv** [run-llama/llama_deploy#99]
@logan-markewich your last tag version 0.0.4 didn't make it to pypi. It would be great to add autobuild and autopush on tag in main. Perhaps some variation of the below?

```
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install
        
      - name: Build package
        run: poetry build
        
      - name: Install twine
        run: pip install twine                

      - name: Publish to PyPI
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && startsWith(github.ref, 'refs/tags/')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: twine upload --verbose dist/*
```
